from app.api import api_bp
from app import db
from app.models import Outline, Volume, Chapter, Project
from flask import request, jsonify
import json

# 大纲相关接口
@api_bp.route('/api/outlines', methods=['POST'])
def create_outline():
    data = request.json
    
    new_outline = Outline(
        project_id=data['project_id'],
        title=data['title'],
        content=data.get('content', ''),
        story_model=data.get('story_model', ''),
        version=data.get('version', 1)
    )
    db.session.add(new_outline)
    db.session.commit()
    return jsonify(new_outline.to_dict()), 201

@api_bp.route('/api/projects/<int:id>/outline', methods=['GET'])
def get_project_outline(id):
    outlines = Outline.query.filter_by(project_id=id).order_by(Outline.version.desc()).all()
    result = [outline.to_dict() for outline in outlines]
    return jsonify(result)

@api_bp.route('/api/outlines/<int:id>', methods=['GET'])
def get_outline(id):
    outline = Outline.query.get(id)
    if not outline:
        return jsonify({'error': 'Outline not found'}), 404
    return jsonify(outline.to_dict())

@api_bp.route('/api/outlines/<int:id>', methods=['PUT'])
def update_outline(id):
    outline = Outline.query.get(id)
    if not outline:
        return jsonify({'error': 'Outline not found'}), 404
    
    data = request.json
    outline.title = data.get('title', outline.title)
    outline.content = data.get('content', outline.content)
    outline.story_model = data.get('story_model', outline.story_model)
    outline.version = data.get('version', outline.version)
    
    db.session.commit()
    return jsonify(outline.to_dict())

@api_bp.route('/api/outlines/<int:id>', methods=['DELETE'])
def delete_outline(id):
    outline = Outline.query.get(id)
    if not outline:
        return jsonify({'error': 'Outline not found'}), 404
    
    db.session.delete(outline)
    db.session.commit()
    return jsonify({'message': 'Outline deleted successfully'})

# AI生成大纲
@api_bp.route('/api/ai/generate_outline', methods=['POST'])
def generate_outline():
    data = request.json
    project_id = data.get('project_id')
    story_model = data.get('story_model', 'hero_journey')
    params = data.get('params', {})
    
    # 这里应该调用AI服务生成大纲
    # 暂时返回模拟数据
    mock_outline = {
        'title': 'Generated Outline',
        'content': json.dumps({
            'main_plot': 'Main plot generated by AI',
            'sub_plots': ['Sub plot 1', 'Sub plot 2'],
            'key_events': ['Event 1', 'Event 2', 'Event 3'],
            'character_arcs': ['Character arc 1', 'Character arc 2'],
            'theme': 'Generated theme'
        }),
        'story_model': story_model
    }
    
    new_outline = Outline(
        project_id=project_id,
        title=mock_outline['title'],
        content=mock_outline['content'],
        story_model=mock_outline['story_model']
    )
    db.session.add(new_outline)
    db.session.commit()
    
    return jsonify(new_outline.to_dict()), 201

# 分解大纲为卷纲
@api_bp.route('/api/outlines/<int:id>/decompose', methods=['POST'])
def decompose_outline(id):
    outline = Outline.query.get(id)
    if not outline:
        return jsonify({'error': 'Outline not found'}), 404
    
    # 这里应该根据大纲内容分解为卷纲
    # 暂时返回模拟数据
    mock_volumes = [
        {
            'title': 'Volume 1',
            'content': 'Introduction and setup',
            'core_conflict': 'Initial conflict',
            'order_index': 1
        },
        {
            'title': 'Volume 2',
            'content': 'Rising action',
            'core_conflict': 'Main conflict development',
            'order_index': 2
        },
        {
            'title': 'Volume 3',
            'content': 'Climax and resolution',
            'core_conflict': 'Final conflict',
            'order_index': 3
        }
    ]
    
    created_volumes = []
    for vol_data in mock_volumes:
        new_volume = Volume(
            project_id=outline.project_id,
            outline_id=outline.id,
            title=vol_data['title'],
            content=vol_data['content'],
            core_conflict=vol_data['core_conflict'],
            order_index=vol_data['order_index']
        )
        db.session.add(new_volume)
        created_volumes.append(new_volume)
    
    db.session.commit()
    return jsonify([volume.to_dict() for volume in created_volumes]), 201

# 卷纲相关接口
@api_bp.route('/api/volumes/<int:id>', methods=['GET'])
def get_volume(id):
    volume = Volume.query.get(id)
    if not volume:
        return jsonify({'error': 'Volume not found'}), 404
    return jsonify(volume.to_dict())

@api_bp.route('/api/volumes/<int:id>', methods=['PUT'])
def update_volume(id):
    volume = Volume.query.get(id)
    if not volume:
        return jsonify({'error': 'Volume not found'}), 404
    
    data = request.json
    volume.title = data.get('title', volume.title)
    volume.content = data.get('content', volume.content)
    volume.core_conflict = data.get('core_conflict', volume.core_conflict)
    volume.order_index = data.get('order_index', volume.order_index)
    
    db.session.commit()
    return jsonify(volume.to_dict())

@api_bp.route('/api/volumes/<int:id>', methods=['DELETE'])
def delete_volume(id):
    volume = Volume.query.get(id)
    if not volume:
        return jsonify({'error': 'Volume not found'}), 404
    
    db.session.delete(volume)
    db.session.commit()
    return jsonify({'message': 'Volume deleted successfully'})

# 分解卷纲为章纲
@api_bp.route('/api/volumes/<int:id>/decompose', methods=['POST'])
def decompose_volume(id):
    volume = Volume.query.get(id)
    if not volume:
        return jsonify({'error': 'Volume not found'}), 404
    
    # 这里应该根据卷纲内容分解为章纲
    # 暂时返回模拟数据
    mock_chapters = [
        {
            'title': 'Chapter 1',
            'scenes': json.dumps(['Scene 1', 'Scene 2']),
            'characters': json.dumps(['Character 1', 'Character 2']),
            'core_event': 'Introduction of main character',
            'emotional_goal': 'Establish empathy',
            'keywords': json.dumps(['introduction', 'setup']),
            'word_count_estimate': 2000,
            'order_index': 1
        },
        {
            'title': 'Chapter 2',
            'scenes': json.dumps(['Scene 1', 'Scene 2']),
            'characters': json.dumps(['Character 1', 'Character 3']),
            'core_event': 'Introduction of conflict',
            'emotional_goal': 'Create tension',
            'keywords': json.dumps(['conflict', 'tension']),
            'word_count_estimate': 2500,
            'order_index': 2
        }
    ]
    
    created_chapters = []
    for chap_data in mock_chapters:
        new_chapter = Chapter(
            project_id=volume.project_id,
            volume_id=volume.id,
            title=chap_data['title'],
            scenes=chap_data['scenes'],
            characters=chap_data['characters'],
            core_event=chap_data['core_event'],
            emotional_goal=chap_data['emotional_goal'],
            keywords=chap_data['keywords'],
            word_count_estimate=chap_data['word_count_estimate'],
            order_index=chap_data['order_index']
        )
        db.session.add(new_chapter)
        created_chapters.append(new_chapter)
    
    db.session.commit()
    return jsonify([chapter.to_dict() for chapter in created_chapters]), 201

# 章纲相关接口
@api_bp.route('/api/chapters/<int:id>', methods=['PUT'])
def update_chapter_details(id):
    chapter = Chapter.query.get(id)
    if not chapter:
        return jsonify({'error': 'Chapter not found'}), 404
    
    data = request.json
    chapter.title = data.get('title', chapter.title)
    chapter.scenes = data.get('scenes', chapter.scenes)
    chapter.characters = data.get('characters', chapter.characters)
    chapter.core_event = data.get('core_event', chapter.core_event)
    chapter.emotional_goal = data.get('emotional_goal', chapter.emotional_goal)
    chapter.keywords = data.get('keywords', chapter.keywords)
    chapter.word_count_estimate = data.get('word_count_estimate', chapter.word_count_estimate)
    
    db.session.commit()
    return jsonify(chapter.to_dict())

# 章纲评估
@api_bp.route('/api/chapters/<int:id>/evaluate', methods=['GET'])
def evaluate_chapter(id):
    chapter = Chapter.query.get(id)
    if not chapter:
        return jsonify({'error': 'Chapter not found'}), 404
    
    # 这里应该实现章纲评估逻辑
    # 暂时返回模拟数据
    evaluation = {
        'chapter_id': id,
        'function_distribution': {
            'main_plot': 70,
            'character_development': 20,
            'foreshadowing': 10
        },
        'rhythm_evaluation': 'Good',
        'conflict_density': 'Moderate',
        'character_balance': 'Balanced'
    }
    
    return jsonify(evaluation)
