"""add world_id to characters and create character subtables

Revision ID: 15146ceeb53e
Revises: ad66a106a628
Create Date: 2026-02-06 11:30:52.651671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15146ceeb53e'
down_revision: Union[str, Sequence[str], None] = 'ad66a106a628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_ability_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('ability_type', sa.String(length=50), nullable=True),
    sa.Column('ability_name', sa.String(length=255), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('acquired_age', sa.Integer(), nullable=True),
    sa.Column('acquired_method', sa.Text(), nullable=True),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('is_signature', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_backgrounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=True),
    sa.Column('start_age', sa.Integer(), nullable=True),
    sa.Column('end_age', sa.Integer(), nullable=True),
    sa.Column('key_events', sa.Text(), nullable=True),
    sa.Column('influential_people', sa.Text(), nullable=True),
    sa.Column('traumas', sa.Text(), nullable=True),
    sa.Column('turning_points', sa.Text(), nullable=True),
    sa.Column('core_memory', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 使用 batch 模式处理 SQLite 的列添加
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alternative_names', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('importance_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('death_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('appearance_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distinguishing_features', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_character_world', 'worlds', ['world_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('fk_character_world', type_='foreignkey')
        batch_op.drop_column('distinguishing_features')
        batch_op.drop_column('appearance_age')
        batch_op.drop_column('death_date')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('importance_level')
        batch_op.drop_column('role_type')
        batch_op.drop_column('alternative_names')
        batch_op.drop_column('world_id')
    op.drop_table('character_backgrounds')
    op.drop_table('character_ability_details')
    # ### end Alembic commands ###
