"""Add energy and society system tables

Revision ID: 6da419b75647
Revises: e2dacae2afa5
Create Date: 2026-02-06 14:16:27.992005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da419b75647'
down_revision: Union[str, Sequence[str], None] = 'e2dacae2afa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civilizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('civilization_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('development_level', sa.String(length=100), nullable=True),
    sa.Column('population_scale', sa.String(length=100), nullable=True),
    sa.Column('territory_size', sa.String(length=100), nullable=True),
    sa.Column('political_system', sa.Text(), nullable=True),
    sa.Column('economic_system', sa.Text(), nullable=True),
    sa.Column('technological_level', sa.String(length=100), nullable=True),
    sa.Column('magical_level', sa.String(length=100), nullable=True),
    sa.Column('cultural_characteristics', sa.Text(), nullable=True),
    sa.Column('religious_beliefs', sa.Text(), nullable=True),
    sa.Column('taboos', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('historical_origin', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('skill_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('learning_time', sa.String(length=100), nullable=True),
    sa.Column('commonality', sa.String(length=50), nullable=True),
    sa.Column('power_level_required', sa.Integer(), nullable=True),
    sa.Column('energy_consumption', sa.String(length=100), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('typical_users', sa.Text(), nullable=True),
    sa.Column('energy_system_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('energy_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('acquisition_method', sa.Text(), nullable=True),
    sa.Column('storage_method', sa.Text(), nullable=True),
    sa.Column('usage_limitations', sa.Text(), nullable=True),
    sa.Column('common_applications', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('stability', sa.String(length=50), nullable=True),
    sa.Column('interaction_with_other_energies', sa.Text(), nullable=True),
    sa.Column('cultivation_method', sa.Text(), nullable=True),
    sa.Column('typical_manifestations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('lifespan_extension', sa.String(length=100), nullable=True),
    sa.Column('typical_combat_power', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('social_status', sa.String(length=100), nullable=True),
    sa.Column('energy_system_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('civilization_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('influence_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultural_customs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('custom_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('time_period', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('procedures', sa.Text(), nullable=True),
    sa.Column('related_beliefs', sa.Text(), nullable=True),
    sa.Column('variations', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_occupations', sa.Text(), nullable=True),
    sa.Column('privileges', sa.Text(), nullable=True),
    sa.Column('obligations', sa.Text(), nullable=True),
    sa.Column('living_standards', sa.Text(), nullable=True),
    sa.Column('education_access', sa.String(length=100), nullable=True),
    sa.Column('social_mobility', sa.String(length=100), nullable=True),
    sa.Column('percentage_of_population', sa.String(length=50), nullable=True),
    sa.Column('typical_power_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_classes')
    op.drop_table('cultural_customs')
    op.drop_table('civilization_regions')
    op.drop_table('power_levels')
    op.drop_table('energy_systems')
    op.drop_table('common_skills')
    op.drop_table('civilizations')
    # ### end Alembic commands ###
