"""Add extended world setting tables including energy forms, power costs, economic systems, political systems, historical eras, events, figures, tags and relations

Revision ID: d8243956c812
Revises: 6da419b75647
Create Date: 2026-02-06 15:11:14.990962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8243956c812'
down_revision: Union[str, Sequence[str], None] = '6da419b75647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_eras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_year', sa.String(length=100), nullable=True),
    sa.Column('end_year', sa.String(length=100), nullable=True),
    sa.Column('duration_description', sa.Text(), nullable=True),
    sa.Column('main_characteristics', sa.Text(), nullable=True),
    sa.Column('key_technologies', sa.Text(), nullable=True),
    sa.Column('dominant_civilizations', sa.Text(), nullable=True),
    sa.Column('ending_cause', sa.Text(), nullable=True),
    sa.Column('legacy_impact', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_conditions', sa.Text(), nullable=True),
    sa.Column('payment_mechanism', sa.Text(), nullable=True),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('mitigation_methods', sa.Text(), nullable=True),
    sa.Column('accumulation_effect', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('economic_model', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency_name', sa.String(length=255), nullable=True),
    sa.Column('currency_material', sa.Text(), nullable=True),
    sa.Column('denomination_system', sa.Text(), nullable=True),
    sa.Column('exchange_rates', sa.Text(), nullable=True),
    sa.Column('major_industries', sa.Text(), nullable=True),
    sa.Column('trade_routes', sa.Text(), nullable=True),
    sa.Column('trade_partners', sa.Text(), nullable=True),
    sa.Column('resource_dependencies', sa.Text(), nullable=True),
    sa.Column('wealth_distribution', sa.Text(), nullable=True),
    sa.Column('taxation_system', sa.Text(), nullable=True),
    sa.Column('banking_system', sa.Text(), nullable=True),
    sa.Column('economic_challenges', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('energy_system_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_properties', sa.Text(), nullable=True),
    sa.Column('interaction_rules', sa.Text(), nullable=True),
    sa.Column('purification_method', sa.Text(), nullable=True),
    sa.Column('corruption_effects', sa.Text(), nullable=True),
    sa.Column('visual_manifestation', sa.Text(), nullable=True),
    sa.Column('sensory_perception', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['energy_system_id'], ['energy_systems.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('era_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_year', sa.String(length=100), nullable=True),
    sa.Column('end_year', sa.String(length=100), nullable=True),
    sa.Column('location_ids', sa.Text(), nullable=True),
    sa.Column('primary_causes', sa.Text(), nullable=True),
    sa.Column('key_participants', sa.Text(), nullable=True),
    sa.Column('event_sequence', sa.Text(), nullable=True),
    sa.Column('immediate_outcomes', sa.Text(), nullable=True),
    sa.Column('long_term_consequences', sa.Text(), nullable=True),
    sa.Column('historical_significance', sa.Text(), nullable=True),
    sa.Column('conflicting_accounts', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['era_id'], ['historical_eras.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_figures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birth_year', sa.String(length=100), nullable=True),
    sa.Column('death_year', sa.String(length=100), nullable=True),
    sa.Column('birth_place_id', sa.Integer(), nullable=True),
    sa.Column('death_place_id', sa.Integer(), nullable=True),
    sa.Column('primary_role', sa.String(length=100), nullable=True),
    sa.Column('social_class', sa.String(length=100), nullable=True),
    sa.Column('key_achievements', sa.Text(), nullable=True),
    sa.Column('controversies', sa.Text(), nullable=True),
    sa.Column('historical_legacy', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('government_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('power_structure', sa.Text(), nullable=True),
    sa.Column('succession_system', sa.Text(), nullable=True),
    sa.Column('decision_process', sa.Text(), nullable=True),
    sa.Column('administrative_divisions', sa.Text(), nullable=True),
    sa.Column('legal_system', sa.Text(), nullable=True),
    sa.Column('military_organization', sa.Text(), nullable=True),
    sa.Column('diplomatic_style', sa.Text(), nullable=True),
    sa.Column('internal_conflicts', sa.Text(), nullable=True),
    sa.Column('external_threats', sa.Text(), nullable=True),
    sa.Column('political_stability', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilizations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('figure_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=100), nullable=True),
    sa.Column('contribution_level', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('outcome_for_participant', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['historical_events.id'], ),
    sa.ForeignKeyConstraint(['figure_id'], ['historical_figures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip dropping old energy_system table and columns - SQLite doesn't support ALTER constraints
    # These will be handled manually if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    op.drop_table('political_systems')
    op.drop_table('historical_figures')
    op.drop_table('historical_events')
    op.drop_table('entity_tags')
    op.drop_table('energy_forms')
    op.drop_table('economic_systems')
    op.drop_table('tags')
    op.drop_table('power_costs')
    op.drop_table('historical_eras')
    op.drop_table('entity_relations')
    # ### end Alembic commands ###
