"""Add world setting module tables: dimensions, regions, celestial_bodies, natural_laws

Revision ID: e2dacae2afa5
Revises: 397152dcf2f1
Create Date: 2026-02-06 14:08:34.080405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dacae2afa5'
down_revision: Union[str, Sequence[str], None] = '397152dcf2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('mass', sa.String(length=100), nullable=True),
    sa.Column('orbit_period', sa.String(length=100), nullable=True),
    sa.Column('rotation_period', sa.String(length=100), nullable=True),
    sa.Column('distance_from_star', sa.String(length=100), nullable=True),
    sa.Column('surface_temperature', sa.String(length=100), nullable=True),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('satellites', sa.Text(), nullable=True),
    sa.Column('magical_properties', sa.Text(), nullable=True),
    sa.Column('cultural_significance', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dimension_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_conditions', sa.Text(), nullable=True),
    sa.Column('physical_properties', sa.Text(), nullable=True),
    sa.Column('time_flow', sa.String(length=100), nullable=True),
    sa.Column('spatial_hierarchy', sa.Integer(), nullable=True),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.Column('magic_concentration', sa.String(length=50), nullable=True),
    sa.Column('element_activity', sa.Text(), nullable=True),
    sa.Column('gravity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('natural_laws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('law_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_principles', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('interactions', sa.Text(), nullable=True),
    sa.Column('common_applications', sa.Text(), nullable=True),
    sa.Column('taboos', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('parent_region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geographical_coordinates', sa.Text(), nullable=True),
    sa.Column('climate', sa.String(length=100), nullable=True),
    sa.Column('terrain', sa.Text(), nullable=True),
    sa.Column('area_size', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('strategic_importance', sa.Integer(), nullable=True),
    sa.Column('controlling_faction_id', sa.Integer(), nullable=True),
    sa.Column('danger_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    op.drop_table('natural_laws')
    op.drop_table('dimensions')
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
