"""Add ai_generation_checkpoint and concept_merge_records tables

Revision ID: f1a2b3c4d5e6
Revises: e2dacae2afa5
Create Date: 2026-03-09 10:30:00.000000

"""
from typing import Sequence, Union
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, Sequence[str], None] = 'd8243956c812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 ai_generation_checkpoint 表
    op.create_table('ai_generation_checkpoint',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stage', sa.String(length=50), nullable=False),
        sa.Column('checkpoint_type', sa.String(length=50), nullable=True),
        sa.Column('checkpoint_data', sa.Text(), nullable=True),
        sa.Column('progress_percent', sa.Integer(), nullable=True, default=0),
        sa.Column('status', sa.String(length=20), nullable=True, default='in_progress'),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 为 session_id 创建索引
    op.create_index(
        'ix_ai_generation_checkpoint_session_id',
        'ai_generation_checkpoint',
        ['session_id']
    )
    
    # 创建 concept_merge_records 表
    op.create_table('concept_merge_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('concept_type', sa.String(length=50), nullable=False),
        sa.Column('source_concepts', sa.Text(), nullable=True),
        sa.Column('merged_concept', sa.Text(), nullable=True),
        sa.Column('attribute_changes', sa.Text(), nullable=True),
        sa.Column('similarity_score', sa.Float(), nullable=True),
        sa.Column('merge_strategy', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 为 session_id 创建索引
    op.create_index(
        'ix_concept_merge_records_session_id',
        'concept_merge_records',
        ['session_id']
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index('ix_concept_merge_records_session_id', table_name='concept_merge_records')
    op.drop_index('ix_ai_generation_checkpoint_session_id', table_name='ai_generation_checkpoint')
    
    # 删除表
    op.drop_table('concept_merge_records')
    op.drop_table('ai_generation_checkpoint')
    
    # ### end Alembic commands ###
